apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: mlflow-secrets-provider
  namespace: {{ .Values.namespace }}
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "churn-mlops/mlflow-tracking-uri"
        objectType: "secretsmanager"
        jmesPath:
          - path: "MLFLOW_TRACKING_URI"
            objectAlias: "MLFLOW_TRACKING_URI"
  secretObjects:
    - secretName: mlflow-secrets-csi
      type: Opaque
      data:
        - objectName: "MLFLOW_TRACKING_URI"
          key: tracking-uri
