apiVersion: v1
kind: ServiceAccount
metadata:
  name: churn-prediction-sa
  namespace: {{ .Values.namespace }}
  labels:
    app: churn-prediction-api
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.irsa.roleArn | quote }}
