apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: churn-prediction-api
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - churn-mlops
  selector:
    matchLabels:
      app: churn-prediction-api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s