# ─────────────────────────────────────────────────────────────────────────────
# modules/ec2/main.tf
#
# New MLflow EC2 instance with:
#   - Latest Amazon Linux 2023 AMI (fetched dynamically via data source)
#   - TLS key pair generated by Terraform (no manual aws ec2 create-key-pair)
#   - Elastic IP for stable endpoint across stop/start cycles
#   - Systemd service for MLflow auto-restart on reboot
#   - Userdata script that installs and starts MLflow on first boot
# ─────────────────────────────────────────────────────────────────────────────

locals {
  base_tags = merge(
    {
      Project     = var.project
      Environment = var.environment
      ManagedBy   = "Terraform"
      Module      = "ec2"
    },
    var.additional_tags
  )

  name_prefix = "${var.project}-${var.environment}"
}

# ─────────────────────────────────────────
# AMI - Latest Amazon Linux 2023
#
# data source fetches the most recent AL2023 AMI at apply time.
# WHY AL2023 over AL2 or Ubuntu:
#   - AWS-maintained, security patches within 24hrs of CVE disclosure
#   - dnf package manager (replaces yum), faster package resolution
#   - Ships with Python 3.9+, no manual install needed
#   - IMDSv2 enforced by default - protects against SSRF attacks on metadata API
# ─────────────────────────────────────────

data "aws_ami" "amazon_linux_2023" {
  most_recent = true
  owners      = ["amazon"]

  filter {
    name   = "name"
    values = ["al2023-ami-2023*-x86_64"]
  }

  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }

  filter {
    name   = "state"
    values = ["available"]
  }
}

# ─────────────────────────────────────────
# TLS Key Pair
#
# Generates RSA key pair inside Terraform state.
# Private key stored in state (encrypted at rest via S3 SSE).
# Public key registered with AWS as EC2 key pair.
# WHY generate in Terraform vs manual creation:
#   - No manual step - fully reproducible infra
#   - Key rotatable by tainting this resource and re-applying
#   - Private key accessible via terraform output for SSH debugging
# ─────────────────────────────────────────

resource "tls_private_key" "mlflow" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

resource "aws_key_pair" "mlflow" {
  key_name   = "${local.name_prefix}-mlflow-key"
  public_key = tls_private_key.mlflow.public_key_openssh

  tags = merge(local.base_tags, {
    Name = "${local.name_prefix}-mlflow-key"
  })
}

# ─────────────────────────────────────────
# EC2 Instance
# ─────────────────────────────────────────

resource "aws_instance" "mlflow" {
  ami                    = data.aws_ami.amazon_linux_2023.id
  instance_type          = var.instance_type
  subnet_id              = var.subnet_id
  vpc_security_group_ids = var.security_group_ids
  key_name               = aws_key_pair.mlflow.key_name
  iam_instance_profile   = var.iam_instance_profile_name

  # IMDSv2 enforced - prevents SSRF attacks from reading instance metadata.
  # Without this, a compromised app on the instance could steal IAM credentials
  # via curl http://169.254.169.254/latest/meta-data/iam/security-credentials/
  metadata_options {
    http_endpoint               = "enabled"
    http_tokens                 = "required" # IMDSv2 - token required
    http_put_response_hop_limit = 1          # blocks container SSRF
  }

  # Root volume: 20 GB gp3.
  # MLflow server itself is small - space needed for pip cache during install
  # and temporary artifact staging before S3 upload.
  root_block_device {
    volume_type           = "gp3"
    volume_size           = 20
    encrypted             = true
    delete_on_termination = true

    tags = merge(local.base_tags, {
      Name = "${local.name_prefix}-mlflow-root-vol"
    })
  }

  # Userdata: runs once on first boot as root.
  # templatefile() renders the script with actual variable values substituted.
  # Changes to userdata do NOT restart existing instances - they only apply
  # to new instances. To reprovision: taint the instance and re-apply.
  user_data = templatefile("${path.module}/userdata.sh.tpl", {
    mlflow_port      = var.mlflow_port
    rds_endpoint     = var.rds_endpoint
    db_secret_arn    = var.db_secret_arn # Secrets Manager ARN — no plaintext password
    artifacts_bucket = var.artifacts_bucket_name
    region           = var.region
  })

  # Ensure EIP is not the bottleneck - instance must exist before EIP association.
  depends_on = [aws_key_pair.mlflow]

  tags = merge(local.base_tags, {
    Name = "${local.name_prefix}-mlflow-server"
  })

  lifecycle {
    # AMI ID changes when AWS releases a new AL2023 version.
    # Without this, every terraform plan would show a diff and try to
    # replace the instance. Ignore AMI drift - only replace on explicit retaint.
    ignore_changes = [ami, user_data]
  }
}

# ─────────────────────────────────────────
# Elastic IP
#
# Stable public IP across stop/start cycles.
# Without EIP: EC2 public IP changes on every start → MLflow URI breaks
# → Secrets Manager update needed → pod restart needed. EIP avoids this chain.
# ─────────────────────────────────────────

resource "aws_eip" "mlflow" {
  domain   = "vpc"
  instance = aws_instance.mlflow.id

  depends_on = [aws_instance.mlflow]

  tags = merge(local.base_tags, {
    Name = "${local.name_prefix}-mlflow-eip"
  })
}
