namespace: churn-mlops

replicaCount: 2

image:
  repository: 011528270076.dkr.ecr.us-east-1.amazonaws.com/churn-prediction-api
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "500m"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

mlflow:
  trackingUri: "http://10.0.1.225:5000"

probes:
  liveness:
    path: /health
    initialDelaySeconds: 40
    periodSeconds: 30
  readiness:
    path: /health
    initialDelaySeconds: 40
    periodSeconds: 10

serviceMonitor:
  enabled: true
  namespace: monitoring
irsa:
  roleArn: "arn:aws:iam::011528270076:role/churn-mlops-irsa-role"

streaming:
  apiUrl: "http://a3bb3c740fb3747d88b007cade5f9bd4-405783512.us-east-1.elb.amazonaws.com"

deployment:
  enabled: false

rollout:
  enabled: true

canaryTest:
  version: "v3"

istio:
  enabled: true
