apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: churn-prediction-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/part-of: churn-mlops
    tier: application
spec:
  project: default
  source:
    repoURL: https://github.com/Himanshu9001/MLOps-Projects.git
    targetRevision: main
    path: helm/churn-mlops
    helm:
      valueFiles:
        - values.yaml
      releaseName: churn-mlops
  destination:
    server: https://kubernetes.default.svc
    namespace: churn-mlops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: churn-prediction-api
      jsonPointers:
        - /spec/replicas
    - group: argoproj.io
      kind: Rollout
      name: churn-prediction-api
      jsonPointers:
        - /spec/replicas
    - group: networking.istio.io
      kind: VirtualService
      name: churn-prediction-api-vsvc
      jsonPointers:
        - /spec/http
    - group: networking.istio.io
      kind: DestinationRule
      name: churn-prediction-api-destrule
      jsonPointers:
        - /spec/subsets
