apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/part-of: churn-mlops
    tier: observability
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: "70.*"
    helm:
      releaseName: prometheus
      values: |
        grafana:
          adminPassword: admin123
          service:
            type: LoadBalancer
          persistence:
            enabled: false
        prometheus:
          prometheusSpec:
            retention: 7d
            resources:
              requests:
                memory: "256Mi"
                cpu: "250m"
              limits:
                memory: "512Mi"
                cpu: "500m"
        alertmanager:
          alertmanagerSpec:
            resources:
              requests:
                memory: "128Mi"
                cpu: "100m"
        nodeExporter:
          enabled: true
        kubeStateMetrics:
          enabled: true
        prometheusOperator:
          admissionWebhooks:
            enabled: false
          tls:
            enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
